/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all of your component files.
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "primary": "#004ac6",
        "primary-container": "#2563eb",
        "on-primary": "#ffffff",
        "on-primary-container": "#eeefff",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary-fixed": "#00174b",
        "on-primary-fixed-variant": "#003ea8",
        "inverse-primary": "#b4c5ff",
        "secondary": "#505f76",
        "secondary-container": "#d0e1fb",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#54647a",
        "secondary-fixed": "#d3e4fe",
        "secondary-fixed-dim": "#b7c8e1",
        "on-secondary-fixed": "#0b1c30",
        "on-secondary-fixed-variant": "#38485d",
        "tertiary": "#00614b",
        "tertiary-container": "#007c60",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#b7ffe3",
        "tertiary-fixed": "#64fbce",
        "tertiary-fixed-dim": "#3fdeb3",
        "on-tertiary-fixed": "#002117",
        "on-tertiary-fixed-variant": "#00513e",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "surface": "#f7f9fb",
        "surface-bright": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-variant": "#e0e3e5",
        "surface-tint": "#0053db",
        "surface-container": "#eceef0",
        "surface-container-low": "#f2f4f6",
        "surface-container-high": "#e6e8ea",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "on-surface": "#191c1e",
        "on-surface-variant": "#434655",
        "on-background": "#191c1e",
        "background": "#f7f9fb",
        "outline": "#737686",
        "outline-variant": "#c3c6d7",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "warning-orange": "#f97316",
        "macro-carb": "#FFD700",
        "macro-protein": "#2563EB",
        "macro-fat": "#EC4899",
      },
      fontFamily: {
        "headline": ["Manrope-Bold"],
        "body": ["PlusJakartaSans-Regular"],
        "label": ["PlusJakartaSans-Medium"],
      }
    },
  },
  plugins: [],
}
